// flow-typed signature: 12d0e11a0f97f371e005045e0d5e96a8
// flow-typed version: <<STUB>>/fscreen_v1.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fscreen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fscreen' {
  declare export default {
    fullscreenEnabled: boolean,
    fullscreenElement: HTMLElement,
    requestFullscreen: (elem: HTMLElement) => void,
    requestFullscreenFunction: (elem: HTMLElement) => void,
    exitFullscreen: () => void,
    onfullscreenchange: (ev: Event) => void,
    addEventListener: (name: 'fullscreenchange', ev: Event, options: {}) => void,
    removeEventListener: (name: 'fullscreenchange', ev: Event, options: {}) => void,
    onfullscreenerror: (ev: Event) => void,
    addEventListener: (name: 'fullscreenerror', ev: Event, options: {}) => void,
    removeEventListener: (name: 'fullscreenerror', ev: Event, options: {}) => void,
  };
}
